#!/bin/sh

do_start() {
	# setup poe-fan and zigbee-gateway
	modprobe rpi-poe-fan
	
	# setup cp210x (only needed as helper for zigbee2mqtt container)
	modprobe cp210x
	for i in $(ls /sys/bus/usb-serial/drivers/cp210x/ 2>/dev/null)
	do
		if [[ "$i" =~ "tty" ]] 
		then
			ln -s /dev/$i /dev/cp210x
			break
		fi
	done

	# wait till network is really up
	while ! mount | grep -q cluster-data
	do
		echo "nfs mount loop"
		mount -a
		sleep 1
	done
	
	# setup worker
	MAC=$(cat /sys/class/net/eth0/address | tr -d :)
	if [ ! -d /mnt/cluster-data/$MAC ]
	then
		mkdir -p /mnt/cluster-data/$MAC
	fi
	
	# set hostname
        echo 'dockerclust-'${MAC}'' > /etc/hostname

	mkdir -p /etc/docker
        echo '{ "data-root": "/mnt/cluster-data/'${MAC}'" }' > /etc/docker/daemon.json
	ln -s /mnt/cluster-data/$MAC /var/lib/docker # FIX: data-root is not enaugh..
}

do_stop() {
	echo "S99prepareSlave: nothing to do - single shot script"
}

case "$1" in
        start)
		do_start
                ;;
        stop)
		do_stop
                ;;
        restart)
		do_stop
                sleep 1
		do_start
                ;;
	*)
                echo "Usage: $0 {start|stop|restart}"
                exit 1
esac
