#!/bin/sh

do_start() {
	# setup poe-fan and zigbee-gateway
	modprobe rpi-poe-fan
	modprobe cp210x

	# wait till network is really up
	while [ ! -f /mnt/cluster-data/slave-token.txt ]
	do
		echo "nfs mount loop"
		mount -a
		sleep 1
	done
	
	# setup worker
	MAC=$(cat /sys/class/net/eth0/address | tr -d :)
	if [ ! -d /mnt/cluster-data/$MAC ]
	then
		mkdir -p /mnt/cluster-data/$MAC
		docker swarm join --token $(cat /mnt/cluster-data/slave-token.txt) 5.5.5.1:2377
		sleep 3
		cp -r /var/lib/docker/swarm/* /mnt/cluster-data/$MAC/
	else
		/etc/init.d/S*dockerd stop
		rm /var/lib/docker/swarm/*
		cp -r /mnt/cluster-data/$MAC/* /var/lib/docker/swarm/
		sleep 3
	fi

	# restart docker in later runlevel state to be sure DOCKER_RAMDISK=true env is working
	export DOCKER_RAMDISK=true
	/etc/init.d/S*dockerd restart
}

do_stop() {
	echo "S99prepareSlave: nothing to do - single shot script"
}

case "$1" in
        start)
		do_start
                ;;
        stop)
		do_stop
                ;;
        restart)
		do_stop
                sleep 1
		do_start
                ;;
	*)
                echo "Usage: $0 {start|stop|restart}"
                exit 1
esac
