#!/bin/sh

# TODO: implement error checks and make it robust if master crashes and reboots (ISCSI and NFS)
### setup script-environment ###
# to manipulate env, edit /boot/dockerclust.conf and override the target env variables
MASTER_IFACE="eth0" # can be ignored if CLUSTER_IFACE + GATEWAY_CLUSTER is setted statically and USE_VLANS is false (for env without vlans)
CLUSTER_VLAN="5" 
GATEWAY_VLAN="1"
CLUSTER_IFACE="${MASTER_IFACE}.${CLUSTER_VLAN}"
GATEWAY_IFACE="${MASTER_IFACE}.${GATEWAY_VLAN}"
SLAVE_IFACE="eth0"
USE_VLANS="true"
DISK="mmcblk0"
BOOT_PART="1"
DATA_PART="2"
MAC_MASTER=$(cat /sys/class/net/${MASTER_IFACE}/address | tr -d :)
MAC_SLAVE=$(cat /sys/class/net/${SLAVE_IFACE}/address | tr -d :)
VG="vg_data"
LV_SHARE="lv_share"
LV_MASTER="lv_${MAC_MASTER}"
LV_SLAVE="lv_${MAC_SLAVE}"
SHARE_MOUNT="/mnt/cluster-data"
DOCKER_MOUNT="/mnt/docker-root"
ISCSI_LV_SIZE="10G"
ISCSI_TARGET="iqn.2025-06.io.dockerclust:docker-root"
GATEWAY_SUBNET="255.255.255.224"
GATEWAY_IPV4="10.5.5.2"
GATEWAY_GW="10.5.5.1"
CLUSTER_SUBNET="255.255.255.248"
CLUSTER_IPV4="172.16.5.1"
CLUSTER_NET="172.16.5.0/29" # !!network must match with CLUSTER_IPV4 and CLUSTER_SUBNET!!
CLUSTER_DHCP_RANGE="172.16.5.2,172.16.5.6,24h" # !!range must match with CLUSTER_IPV4, CLUSTER_SUBNET and CLUSTER_IPV4!!
NTP_SERVER="0.europe.pool.ntp.org"
DNS_SERVER="193.110.81.0" # dns0.eu dns-server
DISK_SIGNATURE=$(dd if=/dev/${DISK} bs=1 skip=440 count=4 2>/dev/null | xxd -p)
NODE_TYPE=$(if [[ "$DISK_SIGNATURE" == "55555555" ]]; then echo master; else echo slave; fi) # check for dockerclust disk-signature
DATA_PART_NAME=$(if [[ "$DISK" == nvme* || "$DISK" == mmc* ]]; then echo "${DISK}p${DATA_PART}"; else echo "${DISK}${DATA_PART}"; fi)
BOOT_PART_NAME=$(if [[ "$DISK" == nvme* || "$DISK" == mmc* ]]; then echo "${DISK}p${BOOT_PART}"; else echo "${DISK}${BOOT_PART}"; fi)

# dynamic global variables
LUN_MAPPING=""


write_master_interfaces() {
	mkdir -p /etc/network
	cat <<EOF > /etc/network/interfaces
auto lo
iface lo inet loopback

auto $MASTER_IFACE
iface $MASTER_IFACE inet manual

auto $CLUSTER_IFACE
iface $CLUSTER_IFACE inet static
        address $CLUSTER_IPV4
        netmask $CLUSTER_SUBNET

auto $GATEWAY_IFACE
iface $GATEWAY_IFACE inet static
        address $GATEWAY_IPV4
        netmask $GATEWAY_SUBNET
        gateway $GATEWAY_GW
EOF
}

write_master_chrony() {
	cat <<EOF > /etc/chrony.conf
pool $NTP_SERVER iburst
keyfile /var/lib/chrony/chrony.keys
driftfile /var/lib/chrony/chrony.drift
logdir /var/log/chrony
maxupdateskew 100.0
makestep 1 3
local stratum 8
allow $CLUSTER_NET
EOF
}

write_master_create_iscsi_lv() {
	cat <<EOF > /usr/bin/create-iscsi-lv.sh
#!/bin/sh

ACTION="\$1"
MAC=\$(echo "\$2" | tr -d ':' | tr 'A-Z' 'a-z')
IP="\$3"
HOSTNAME="\$4"

# Only act on new leases
if [ "\$ACTION" = "add" ] && [ "\$MAC" != "$MAC_MASTER" ]; then
    LV_NAME="lv_\$MAC"

    # Check if LV already exists
    if ! lvdisplay "/dev/${VG}/\$LV_NAME" > /dev/null 2>&1; then
	lvcreate -n \$LV_NAME -l10%VG $VG
	vgchange -ay $VG
        mkfs.btrfs /dev/${VG}/\$LV_NAME

	LUNS=\$(tgtadm --lld iscsi --mode target --op show | grep 'LUN:' | awk '{print \$2}' | tr -d ':')
	NEXT_LUN=1
	while echo "\$LUNS" | grep -qw "\$NEXT_LUN"
	do
		NEXT_LUN=\$((\$NEXT_LUN + 1))
	done
	tgtadm --lld iscsi --op new --mode logicalunit --tid 1 --lun \$NEXT_LUN -b /dev/${VG}/\$LV_NAME
	mount -o remount,rw /boot
	echo "\$LV_NAME:\$NEXT_LUN" >> /boot/lun-mapping.txt
	sync
	mount -o remount,ro /boot
        logger "Created LV \$LV_NAME for DHCP client \$MAC (\$IP \$HOSTNAME)"
    fi
fi

exit 0
EOF
	chmod +x /usr/bin/create-iscsi-lv.sh
}

write_master_fstab() {
	cat <<EOF > /etc/fstab
tmpfs	/tmp	tmpfs	mode=1777	0	0
tmpfs	/run	tmpfs	mode=0755,nosuid,nodev	0	0
tmpfs	/var	tmpfs	defaults	0	0
tmpfs	/root	tmpfs	defaults	0	0
/dev/$VG/$LV_SHARE	$SHARE_MOUNT	btrfs	defaults	0	0
/dev/$VG/$LV_MASTER	$DOCKER_MOUNT	btrfs	defaults	0	0
/dev/$BOOT_PART_NAME	/boot/	vfat	defaults,ro	0	2
EOF
}

write_master_exports() {
	cat <<EOF > /etc/exports
$SHARE_MOUNT $CLUSTER_NET(rw,no_root_squash,no_subtree_check)
EOF
}

write_master_dnsmasq() {
	cat <<EOF > /etc/dnsmasq.conf
interface=$CLUSTER_IFACE
no-dhcp-interface=$MASTER_IFACE
no-dhcp-interface=$GATEWAY_IFACE
dhcp-range=$CLUSTER_DHCP_RANGE
enable-tftp
tftp-root=/tftpboot
pxe-service=0,"Raspberry Pi Boot"
dhcp-option=42,$CLUSTER_IPV4 # ntp-server
dhcp-option=3,$CLUSTER_IPV4 # gateway
dhcp-option=6,$CLUSTER_IPV4 # dns-server
dhcp-script=/usr/bin/create-iscsi-lv.sh
server=$DNS_SERVER
EOF
}

write_slave_interfaces() {
	mkdir -p /etc/network
	cat <<EOF > /etc/network/interfaces
auto lo
iface lo inet loopback

# S39dockerclust init script is managing udhcpcd - let the interface manual
auto $SLAVE_IFACE
iface $SLAVE_IFACE inet manual
EOF
}

write_slave_chrony() {
	cat <<EOF > /etc/chrony.conf
server $CLUSTER_IPV4 iburst prefer
keyfile /var/lib/chrony/chrony.keys
driftfile /var/lib/chrony/chrony.drift
logdir /var/log/chrony
maxupdateskew 100.0
makestep 1 3
EOF
}

write_slave_create_iscsi_lv() {
	cat <<EOF > /usr/bin/create-iscsi-lv.sh
EOF
	chmod +x /usr/bin/create-iscsi-lv.sh
}

write_slave_fstab() {
	cat <<EOF > /etc/fstab
tmpfs	/tmp	tmpfs	mode=1777	0	0
tmpfs	/run	tmpfs	mode=0755,nosuid,nodev	0	0
tmpfs	/var	tmpfs	defaults	0	0
tmpfs	/root	tmpfs	defaults	0	0
$LUN_MAPPING	$DOCKER_MOUNT	btrfs	defaults	0	0
$CLUSTER_IPV4:$SHARE_MOUNT    $SHARE_MOUNT       nfs     rw,vers=3,hard,noatime,nolock,noacl,exec,dev,suid       0       0
EOF
}

write_slave_exports() {
	cat <<EOF > /etc/exports
EOF
}

write_slave_dnsmasq() {
	cat <<EOF > /etc/dnsmasq.conf
EOF
}

do_start() {
	### early stuff ###
	## setup required system paths
	echo "setup early stuff"
	mkdir -p /var/lib/misc
	mkdir -p /var/lib/nfs
	mkdir -p /var/run
	mkdir -p /root
	mkdir -p /etc/dropbear
	touch /etc/resolv.conf
	mount

	## setup overrides and slave network
	if [[ "$NODE_TYPE" == master ]]
	then
		## setup environment
		mkdir -p /boot
		mount -t vfat -o ro /dev/${BOOT_PART_NAME} /boot
		. /boot/dockerclust.conf # override variables
	else
		## special slave networking stuff
		# slave needs at the very beginning network
		echo "setup networking"
		write_${NODE_TYPE}_interfaces
		ifup $SLAVE_IFACE
		sleep 2 # wait for network be really up
		udhcpc -i $SLAVE_IFACE
		if [ $? -ne 0 ]
		then
			echo "slave-error: no dhcp lease gotten - abort"
			exit 1 # further execution makes no sense here
		fi

		## setup environment
		cd /tmp
		tftp -g -r dockerclust.conf $CLUSTER_IPV4
		. /tmp/dockerclust.conf # override variables
		cd ~
	fi

	## setup further paths
	mkdir -p ${DOCKER_MOUNT} 
	mkdir -p ${SHARE_MOUNT}
	

	### kernel stuff ###
	echo "setup kernel stuff"
	## setup poe-fan
	modprobe rpi-poe-fan

	## setup cp210x (only needed as helper/workaround for zigbee2mqtt container)
	modprobe cp210x
	for i in $(ls /sys/bus/usb-serial/drivers/cp210x/ 2>/dev/null)
	do
		if [[ "$i" =~ "tty" ]] 
		then
			ln -s /dev/$i /dev/cp210x
			break
		fi
	done


	### block-device stuff ###
	echo "setup block devices"
	## setup storage
	if [[ "$NODE_TYPE" == master ]]
	then
        	if [ ! -b /dev/${DATA_PART_NAME} ]
        	then
			echo -e "n\np\n2\n\n\n t\n2\n8e\nw" | fdisk /dev/${DISK}
			
			# setup lvm			
			partprobe /dev/${DISK}
			pvcreate /dev/${DATA_PART_NAME}
			vgcreate $VG /dev/${DATA_PART_NAME}
			lvcreate -n $LV_SHARE -l20%VG $VG
			lvcreate -n $LV_MASTER -l10%VG $VG
			vgchange -ay $VG
            		mkfs.btrfs /dev/${VG}/${LV_SHARE}
            		mkfs.btrfs /dev/${VG}/${LV_MASTER}
		else
			vgchange -ay $VG
		fi
	fi


	### networking stuff ###
	echo "setup networking"
	## setup iface config
	if [[ "$NODE_TYPE" == master ]]
	then
		write_${NODE_TYPE}_interfaces
	fi
	
	## setup vlans
	if [[ "$NODE_TYPE" == master ]]
	then
		if [ "$USE_VLANS" = true ] 
		then
        		ip link add link $MASTER_IFACE name $CLUSTER_IFACE type vlan id $CLUSTER_VLAN
        		ip link add link $MASTER_IFACE name $GATEWAY_IFACE type vlan id $GATEWAY_VLAN
		fi
		ifup $MASTER_IFACE
        	ifup $CLUSTER_IFACE
        	ifup $GATEWAY_IFACE
	fi
	
	## setup ip routing
	if [[ "$NODE_TYPE" == master ]]
	then
		iptables -t nat -A POSTROUTING -o $GATEWAY_IFACE -j MASQUERADE
		iptables -A FORWARD -i $GATEWAY_IFACE -o $CLUSTER_IFACE -m state --state RELATED,ESTABLISHED -j ACCEPT
		iptables -A FORWARD -i $CLUSTER_IFACE -o $GATEWAY_IFACE -j ACCEPT
	fi

	## setup nfs
	sleep 2 # wait for network be really up
	write_${NODE_TYPE}_exports
	rpcbind

	## setup iscsi
	if [[ "$NODE_TYPE" == master ]]
	then
		tgtd
		sleep 2 # wait for tgtd be really running
		tgtadm --lld iscsi --op new --mode target --tid 1 -T $ISCSI_TARGET
		LV_LIST=$(lvs --noheadings -o lv_path | awk '{print $1}')
		LUN=1
		mount -o remount,rw /boot
		rm /boot/lun-mapping.txt
		for i in $LV_LIST 
		do
			tgtadm --lld iscsi --mode logicalunit --op new --tid 1 --lun $LUN -b $i
			echo "Added $i as LUN $LUN to target $TID"
			echo "$(echo $i | cut -d'/' -f4):$LUN" >> /boot/lun-mapping.txt
			LUN=$(($LUN + 1))
		done
		sync
		mount -o remount,ro /boot
		tgtadm --lld iscsi --op bind --mode target --tid 1 -I $CLUSTER_IPV4
	else
		mkdir -p /etc/iscsi
		echo "InitiatorName=$(iscsi-iname)" > /etc/iscsi/initiatorname.iscsi
		iscsid
		sleep 2 # wait for iscsiadm be really running
		TARGET=$(iscsiadm -m discovery -t sendtargets -p $CLUSTER_IPV4)
		iscsiadm -m node -T $TARGET -p $CLUSTER_IPV4 --login
		sleep 1 # wait for login

		cd /tmp
		tftp -g -r lun-mapping.txt $CLUSTER_IPV4
		LUN=$(cat lun-mapping.txt | grep $MAC_SLAVE | cut -d':' -f2)
		cd ~

		LUN_MAPPING=$(
		iscsiadm -m session -P 3 | \
		awk -v lun="$LUN" '
		  $0 ~ "Lun: " lun"$" {
		    getline
		    if ($0 ~ /Attached scsi disk/) {
		      for (i=1; i<=NF; i++) {
		        if ($i == "disk") {
		          print "/dev/" $(i+1)
		          exit
		        }
		      }
		    }
		  }
		')       
	fi

	## setup dnsmasq
	write_${NODE_TYPE}_dnsmasq
	write_${NODE_TYPE}_create_iscsi_lv
	
	## setup chrony
	# fix expired certificate error on docker swarm after chrony sync
	date -s "2025-01-01 00:00"
	write_${NODE_TYPE}_chrony

	
	### misc stuff ###
	echo "setup misc"
	## setup docker
	mkdir -p /etc/docker
        echo '{ "data-root": "'${DOCKER_MOUNT}'" }' > /etc/docker/daemon.json
	
	## setup tftpboot
	if [[ "$NODE_TYPE" == master ]]
	then
		rm -rf /tftpboot/
		mkdir -p /boot/
		ln -s /boot/ /tftpboot
	fi

	## setup hostname
	if [[ "$NODE_TYPE" == master ]]
	then
        	echo 'dockerclust-'${MAC_MASTER}'' > /etc/hostname
	else
        	echo 'dockerclust-'${MAC_SLAVE}'' > /etc/hostname
	fi
	
	## setup fstab
	write_${NODE_TYPE}_fstab
	mount -a
}

do_stop() {
	echo "S99prepareCluster: nothing to do - single shot script"
}

case "$1" in
        start)
		do_start
                ;;
        stop)
		do_stop
                ;;
        restart)
		do_stop
                sleep 1
		do_start
                ;;
	*)
                echo "Usage: $0 {start|stop|restart}"
                exit 1
esac
